#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely with
# With sleep 2 in between each iteration.
# Displays "I am invincible!!!" when receiving SIGTERM signal

while true

do

  echo "To infinity and beyond"

  sleep 2

  trap 'echo "I am invincible!!!"' SIGTERM 

done
