#!/usr/bin/env bash
#A script that displays the contents of the file `/etc/passwd`.
# It should only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
