#!/usr/bin/env bash
#Script that displays Best School 10 times
#Displays "Hi!" on a new line at 9th iteration

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
	done
