#!/usr/bin/env bash
#Script that displays Best School 10 times
#Displays "Hi!" on a new line at 9th iteration
i=1
while [ $i -le 10 ] do
	if [ $i = 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$(( i + 1 ))
done
