#!/usr/bin/env bash
#Script that gives you information about the school file.
#Check if the file exists and print:
#	If the file exists: school file exists
#	If the file does not exist: school file does not exist
#If the file exists, print:
#	If the file is empty: school file is empty
#	If the file is not empty: school file is not empty
#	If the file is a regular file: school is a regular file
#	If the file is not a regular file: (nothing)
if [ -e school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
