#!/usr/bin/env bash
# Script that configures an Ubuntu server as follows:
#	Localhost resolves to 127.0.0.2
#	Facebook.com resolves to 8.8.8.8 and read a given docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
